# Generated by Django 4.2.26 on 2025-11-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d'),
        ),
    ]
